### ISSUE TITLE
Missing info about minor currency units (the "exponent")

### ISSUE THREAD

**Issue by marexv** [maisak/iso.resolvers#3]
Hi this seems to be great library but it would be even better if it had exponent info.

Description taken from wikipedia:

> Treatment of minor currency units (the "exponent")
> The ISO 4217 standard includes a crude mechanism for expressing the relationship between a major currency unit and its corresponding minor currency unit. This mechanism is called the currency "exponent" and assumes a base of 10. For example, USD (the United States dollar) is equal to 100 of its minor currency unit the "cent". So the USD has exponent 2 (10 to the power 2 is 100, which is the number of cents in a dollar). The code JPY (Japanese yen) is given the exponent 0, because its minor unit, the sen, although nominally valued at 1/100 of a yen, is of such negligible value that it is no longer used. ...

What is your opinion on adding this?

**Comment by maisak** [comment]
Great idea! Added.
