### ISSUE TITLE
Remove ISO.4217/codes.xml

### ISSUE THREAD

**Issue by DmitriyBobrovskiy** [maisak/iso.resolvers#6]
Hi,
As far as I understand [that file](https://github.com/maisak/iso.resolvers/blob/232c012b4268abf7bd6b14c861d1951f5ef7fa12/src/ISO.4217/codes.xml) isn't used anywhere, so why is it still in the repo?
I suggest removing it to not confuse any people.

**Comment by maisak** [comment]
That is a source file, in case someone (me included) needs to check out the original. Exactly today used it again to add exponent values.
